### PR TITLE
Refactors JSON helpers module to be standalone

### PR DESCRIPTION
**Pull request by d-Pixie**
Refactors internals to take all dependencies as parameters.
Updates repository savers and loaders to inject any options needed.
Refactors the repository test to use the module directly.
Removes the JSON helper context.

Solves https://github.com/my-codeworks/fortnox-api/issues/52.

### CODE REVIEW

**Comment by ehannes** [comment]
Looking great! I have no objections :)

**Comment by d-Pixie** [comment]
Waiting for CC then merge :)

**Comment by ehannes** [comment]
Or wait, one thing... Give me a minute...

**Comment by d-Pixie** [comment]
*ha ha ha* Sure ...

**Comment by ehannes** [comment]
I was searching for a piece of code that I thought we could replace, but I had already done that :) No further comments. Merge when CC is ready.

**Pull request merged**
